version: "3.5"
#ip=`ifconfig | grep 192 | grep -v grep | awk '{print $2}'`
services:
  etcd:
    container_name: etcd
    image: "bitnami/etcd:latest"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
    ports:
      - 2379:2379
      - 2380:2380
    networks:
      hx_net:
        ipv4_address: 172.22.0.2
  
  # web:
  #   container_name: etcdv3-browser
  #   image: rustyx/etcdv3-browser
  #   environment:
  #     - ETCD=etcd:2379
  #     - EDITABLE=1
  #   ports:
  #     - 8000:8081
  #   restart: always
  #   networks:
  #     hx_net:
  #       ipv4_address: 172.22.0.3

  # e3w:
  #   container_name: e3w
  #   hostname: e3w
  #   image: soyking/e3w:latest
  #   ports:
  #     - "2300:8080"
  #   networks:
  #     hx_net:
  #       ipv4_address: 172.22.0.4

  jeager:
    container_name: jeager
    # image: jaegertracing/all-in-one:latest
    image: scg130/jeager
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
      - "14250:14250"
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
      STORAGE: elasticsearch
      ES_SERVER_URLS: http://elastic:smd013012@elasticsearch:9200 # http://elastic:smd013012@elasticsearch:9200
      SPAN_STORAGE_TYPE: elasticsearch
      ES_TAGS_AS_FIELDS: true
    networks:
      hx_net:
        ipv4_address: 172.22.0.5

  #http://192.168.1.130:7777/hystrix   http://192.168.1.130:81/hystrix.stream  防火墙 81 7777端口打开
  # hystrix:
  #   container_name: hystrix
  #   image: scg130/hystrix
  #   ports:
  #     - 7777:9002
  #   restart: always
  #   networks:
  #     hx_net:
  #       ipv4_address: 172.22.0.6
  
  kanshu-user:
    container_name: kanshu-user-srv
    image: scg130/kanshu-user
    command: /user-service
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWD: ${MYSQL_PASSWD}
      MYSQL_NOVEL_DB: ${MYSQL_NOVEL_DB}
      MYSQL_LOG: ${MYSQL_LOG}
      ETCD_HOST: ${ETCD_HOST}
      TRACER_HOST: ${TRACER_HOST}
      TRACER_PORT: ${TRACER_PORT}
    networks:
      hx_net:
        ipv4_address: 172.22.0.10

  kanshu-novel:
    container_name: kanshu-novel-srv
    image: scg130/kanshu-novel
    command: /novel-service
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWD: ${MYSQL_PASSWD}
      MYSQL_NOVEL_DB: ${MYSQL_NOVEL_DB}
      MYSQL_LOG: ${MYSQL_LOG}
      ETCD_HOST: ${ETCD_HOST}
      TRACER_HOST: ${TRACER_HOST}
      TRACER_PORT: ${TRACER_PORT}
    networks:
      hx_net:
        ipv4_address: 172.22.0.11

  kanshu-runapp:
    container_name: kanshu-runapp
    image: scg130/kanshu-runapp
    command: /micro/runapp
    ports:
      - 2222:2222
      - 81:81
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWD: ${MYSQL_PASSWD}
      MYSQL_NOVEL_DB: ${MYSQL_NOVEL_DB}
      MYSQL_LOG: ${MYSQL_LOG}
      ETCD_HOST: ${ETCD_HOST}
      TRACER_HOST: ${TRACER_HOST}
      TRACER_PORT: ${TRACER_PORT}
      DOMAIN: ${DOMAIN}
      FRONT_URL: ${FRONT_URL}
      PAYPAL_CLIENT_ID: ${PAYPAL_CLIENT_ID}
      PAYPAL_SECRET: ${PAYPAL_SECRET}
      PAYPAL_RETURN_URL: ${PAYPAL_RETURN_URL}
      ALIPAY_APPID: ${ALIPAY_APPID}
      ALIPAY_RSA_PRIVATE_KEY: ${ALIPAY_RSA_PRIVATE_KEY}
      ALIPAY_RSA_PUBLIC_KEY: ${ALIPAY_RSA_PUBLIC_KEY}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      PAYPAL_ENV: local
    networks:
      hx_net:
        ipv4_address: 172.22.0.12

  kanshu-admin:
    container_name: kanshu-admin-srv
    image: scg130/kanshu-admin
    command: /admin-service
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWD: ${MYSQL_PASSWD}
      MYSQL_ADMIN_DB: ${MYSQL_ADMIN_DB}
      MYSQL_LOG: ${MYSQL_LOG}
      ETCD_HOST: ${ETCD_HOST}
      TRACER_HOST: ${TRACER_HOST}
      TRACER_PORT: ${TRACER_PORT}
    networks:
      hx_net:
        ipv4_address: 172.22.0.13

  kanshu-charge:
    container_name: kanshu-charge-srv
    image: scg130/kanshu-charge
    command: /charge-service
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWD: ${MYSQL_PASSWD}
      MYSQL_NOVEL_DB: ${MYSQL_NOVEL_DB}
      MYSQL_LOG: ${MYSQL_LOG}
      ETCD_HOST: ${ETCD_HOST}
      TRACER_HOST: ${TRACER_HOST}
      TRACER_PORT: ${TRACER_PORT}
    networks:
      hx_net:
        ipv4_address: 172.22.0.14

  kanshu-wallet:
    container_name: kanshu-wallet-srv
    image: scg130/kanshu-wallet
    command: /wallet-service
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWD: ${MYSQL_PASSWD}
      MYSQL_NOVEL_DB: ${MYSQL_NOVEL_DB}
      MYSQL_LOG: ${MYSQL_LOG}
      ETCD_HOST: ${ETCD_HOST}
      TRACER_HOST: ${TRACER_HOST}
      TRACER_PORT: ${TRACER_PORT}
    networks:
      hx_net:
        ipv4_address: 172.22.0.15

  kanshu-comment:
    container_name: kanshu-comment-srv
    image: scg130/kanshu-comment
    command: /comment-service
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWD: ${MYSQL_PASSWD}
      MYSQL_NOVEL_DB: ${MYSQL_NOVEL_DB}
      MYSQL_LOG: ${MYSQL_LOG}
      ETCD_HOST: ${ETCD_HOST}
      TRACER_HOST: ${TRACER_HOST}
      TRACER_PORT: ${TRACER_PORT}
    networks:
      hx_net:
        ipv4_address: 172.22.0.16

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.18
    privileged: true
    user: "1000:1000"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - discovery.type=single-node
      - xpack.security.enabled=false # 启用X-Pack安全功能
      - ELASTIC_PASSWORD=smd013012  # 账号 elastic  
    volumes:
      - ./esdata:/usr/share/elasticsearch/data # chmod -R 777 es/*
      - ./eslogs:/usr/share/elasticsearch/logs
    networks:
      hx_net:
        ipv4_address: 172.22.0.17

networks:
  hx_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16
